### ISSUE TITLE
HCopy : LoadData - Cannot read data into memory

### ISSUE THREAD

**Issue by rohanmohapatra** [prosodylab/Prosodylab-Aligner#74]
**The Error is : **
`ERROR [+6253]  LoadData: Cannot read data into memory

  ERROR [+6213]  OpenWaveInput: LoadData failed

  ERROR [+6313]  OpenAsChannel: OpenWaveInput failed

  ERROR [+6316]  OpenBuffer: OpenAsChannel failed

  ERROR [+1050]  OpenParmFile: Config parameters invalid

 FATAL ERROR - Terminating program HCopy

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/Directory/Prosodylab-Aligner/aligner/__main__.py", line 92, in <module>
    corpus = Corpus(args.train, opts)
  File "/home/user/Directory/Prosodylab-Aligner/aligner/corpus.py", line 92, in __init__
    self._extract_features()
  File "/home/user/Directory/Prosodylab-Aligner/aligner/corpus.py", line 220, in _extract_features
    check_call(["HCopy", "-C", self.HCopy_cfg, "-S", self.audio_scp])
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['HCopy', '-C', '/tmp/tmpvwgkkqbe/HCopy.cfg', '-S', '/tmp/tmpvwgkkqbe/audio.scp']' returned non-zero exit status 26`

While Aligning perfectly formatted Wav files, this issue has risen.
The following is the config file:

![image](https://user-images.githubusercontent.com/31756343/48254056-e1a33c00-e42e-11e8-9820-2321384d95ac.png)

Note that I changed SourceFormat from WAVE to WAV. Even this didn't solve the issue.

Attaching _mediainfo of the Wave File used_
-----
General
Complete name                            : /home/user/Directory/tester/sample/test.wav
Format                                   : Wave
File size                                : 144 KiB
Duration                                 : 4s 606ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 256 Kbps

Audio
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, Sign                    : Signed
Codec ID                                 : 1
Duration                                 : 4s 606ms
Bit rate mode                            : Constant
Bit rate                                 : 256 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 16.0 KHz
Bit depth                                : 16 bits
Stream size                              : 144 KiB (100%)

**Comment by rohanmohapatra** [comment]
> 

> The error is coming from the HTK command HCopy and is a read error of some sort, it appears. I am not sure why because I don’t know anything about your setup or the files you’re trying to read. The only way I can debug this Is if I can recreate it locally and exactly. If you want, create a small-as-possible, reproducible and complete example and include all data and commands issued in an email to me.
> […](#)
> On Nov 9, 2018, at 4:22 AM, Rohan Mohapatra ***@***.***> wrote: **The Error is : ** `ERROR [+6253] LoadData: Cannot read data into memory ERROR [+6213] OpenWaveInput: LoadData failed ERROR [+6313] OpenAsChannel: OpenWaveInput failed ERROR [+6316] OpenBuffer: OpenAsChannel failed ERROR [+1050] OpenParmFile: Config parameters invalid FATAL ERROR - Terminating program HCopy Traceback (most recent call last): File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main "main", mod_spec) File "/usr/lib/python3.4/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/user/Directory/Prosodylab-Aligner/aligner/main.py", line 92, in corpus = Corpus(args.train, opts) File "/home/user/Directory/Prosodylab-Aligner/aligner/corpus.py", line 92, in init self._extract_features() File "/home/user/Directory/Prosodylab-Aligner/aligner/corpus.py", line 220, in _extract_features check_call(["HCopy", "-C", self.HCopy_cfg, "-S", self.audio_scp]) File "/usr/lib/python3.4/subprocess.py", line 561, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['HCopy', '-C', '/tmp/tmpvwgkkqbe/HCopy.cfg', '-S', '/tmp/tmpvwgkkqbe/audio.scp']' returned non-zero exit status 26` While Aligning perfectly formatted Wav files, this issue has risen. The following is the config file: Note that I changed SourceFormat from WAVE to WAV. Even this didn't solve the issue. Attaching mediainfo of the Wave File used General Complete name : /home/user/Directory/tester/sample/test.wav Format : Wave File size : 144 KiB Duration : 4s 606ms Overall bit rate mode : Constant Overall bit rate : 256 Kbps Audio Format : PCM Format settings, Endianness : Little Format settings, Sign : Signed Codec ID : 1 Duration : 4s 606ms Bit rate mode : Constant Bit rate : 256 Kbps Channel(s) : 1 channel Sampling rate : 16.0 KHz Bit depth : 16 bits Stream size : 144 KiB (100%) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Sure, Can you send me your email address so that I can mail you a compressed folder with the above mentioned files.

**Comment by kylebgorman** [comment]
It's in my GitHub profile.

**Comment by kylebgorman** [comment]
Closing for inactivity.
