### ISSUE TITLE
FileNotFoundError: phons and taskdict files are not created?

### ISSUE THREAD

**Issue by EvanBialo** [prosodylab/Prosodylab-Aligner#83]
I got the following error: 
`Traceback (most recent call last):
  File "C:/Users/Evan6/PycharmProjects/Discover/src/mai.py", line 54, in <module>
    corpus = Corpus(align, opts)
  File "C:\Users\Evan6\PycharmProjects\Discover\src\corpus.py", line 95, in __init__
    self._prepare_label(labelfiles)
  File "C:\Users\Evan6\PycharmProjects\Discover\src\corpus.py", line 198, in _prepare_label
    temp, self.word_mlf])
  File "C:\Users\Evan6\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Evan6\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Evan6\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Evan6\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

The code is slightly modifed the code, but nothing to do with this. Here are the arguments for the call:
`C:\Users\Evan6\AppData\Local\Temp\tmp3keeds7y\temp
C:\Users\Evan6\AppData\Local\Temp\tmp3keeds7y\words
C:\Users\Evan6\AppData\Local\Temp\tmp3keeds7y\phons
C:\Users\Evan6\AppData\Local\Temp\tmp3keeds7y\taskdict
C:\Users\Evan6\Downloads\librispeech-lexicon.txt`
At first, I thought the issue was that phons and taskdict aren't created, but even when I made those files exist, I still get the error.

**Comment by EvanBialo** [comment]
This was because this wasn't designer for Windows. I added shell=True. in check_call.
Heads up to the developers, the 3rd party windows installation tutorial you linked to is dead. It is on [wayback machine](https://web.archive.org/web/20170531045440/https://linguistics.stonybrook.edu/jiwonyun/papers/Yun_et_al_2016_AH26.pdf) though.
