### ISSUE TITLE
Need to know More about the Execution

### ISSUE THREAD

**Issue by praveen5655** [prosodylab/Prosodylab-Aligner#85]
Do I need to provide both the audio file and text file to get the Output or either one of them

**Comment by kylebgorman** [comment]
Since this is for forced alignment you provide the audio (as a .wav) file and the text (as a .lab) file. If you want it to transcribe for you too, that's speech recognition, and this tool is not set up for that setting, which is quite a bit harder/noisier.

**Comment by praveen5655** [comment]
Thanks for the info. 

When I tried to execute I am getting a error message. Please help me to overcome this problem.

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/www/llp/Prosodylab-Aligner-master/Prosodylab-Aligner-master/aligner/__main__.py", line 116, in <module>
    archive = Archive(args.read)
  File "/var/www/llp/Prosodylab-Aligner-master/Prosodylab-Aligner-master/aligner/archive.py", line 51, in __init__
    unpack_archive(source, base)
  File "/usr/lib/python3.6/shutil.py", line 983, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/usr/lib/python3.6/shutil.py", line 883, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: lang-mod.zip is not a zip file
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/var/www/llp/Prosodylab-Aligner-master/Prosodylab-Aligner-master/aligner/archive.py", line 88, in __del__
    if self.is_tmpdir:
AttributeError: 'Archive' object has no attribute 'is_tmpdir'

**Comment by kylebgorman** [comment]
Hi again,

Our model files are stored as zip files (because they contain several
elements: an acoustic model, a dictionary, a config file, etc.). This is
saying that it tried to load a model from something that is not a zip file,
that's all the error means. You may need to fix the paths you're passing to
the aligner

If you'd like me to help debug this please make a small reproducible
example, including:

* the version you're using (if not the most current version available from
GitHub)
* your OS (version etc.) and Python version
* the exact command(s) you issued, and
* the data files you're using (often you can reproduce the error using just
a single label file/wav file pair), uploaded somewhere online like Gist (
https://gist.github.com/).
