### ISSUE TITLE
No file or directory "HDMan" when run through the browser

### ISSUE THREAD

**Issue by praveen5655** [prosodylab/Prosodylab-Aligner#88]
The aligner runs smoothly when I run it through the command line and giving the results , but its throwing an error whenever I run it from the browser.
Please guide me in solving this.

**Comment by kylebgorman** [comment]
I'm not sure what you mean by "from the browser". Prosodylab-Aligner is a
command-line tool.

I wonder if the error might be related to an incomplete (or not started)
installation of HTK. If that is possible see the instructions here:

https://github.com/prosodylab/Prosodylab-Aligner#install-htk-hidden-markov-toolkit

**Comment by praveen5655** [comment]
Thank you!  I followed all the steps mentioned. But the problem is It only works when I run the command in particular directory 
but When I run the command Outside the directory its giving error file or directory not found.

**Comment by kylebgorman** [comment]
Please provide a simple reproducible example, with data and code used, if you want me to look into this. (I still don't know what you mean by "through the browser".)

**Comment by jplu111** [comment]
Hello, 
I am also receiving a (potentially) similar error. I am running Prosodylab-Aligner through the command-line (terminal) and I receive the following error. The first line below is my command to call the aligner and the very last line has the "HDMan" error. I have also followed all the steps in the GitHub guide for installation. Any help would be great. Thank you!



$ python3 -m aligner -r eng.zip -a /Users/jsmith/Desktop/data -d eng.dict 

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jsmith/Documents/Prosodylab-Aligner/aligner/__main__.py", line 130, in <module>
    corpus = Corpus(args.align, opts)
  File "/Users/jsmith/Documents/Prosodylab-Aligner/aligner/corpus.py", line 95, in __init__
    self._prepare_label(labelfiles)
  File "/Users/jsmith/Documents/Prosodylab-Aligner/aligner/corpus.py", line 177, in _prepare_label
    check_call(["HDMan", "-m",
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'HDMan'

**Comment by kylebgorman** [comment]
It appears you don’t have HDMan installed after all. I’m not sure what else
would account for this error. What happens when you execute:

HDMan -v

at the terminal?

**Comment by jplu111** [comment]
Thank you for the quick response!

I have been able to get it to work by reinstalling HTK.
